# Generated by Django 4.1.3 on 2023-04-14 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AVZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'АВЗ',
                'verbose_name_plural': 'АВЗ',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Статив')),
            ],
            options={
                'verbose_name': 'Статив',
                'verbose_name_plural': 'Стативы',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('БТ', 'Ботаническая'), ('ЧК', 'Чкаловская'), ('ГЕОЛ', 'Геологическая'), ('ПЛ', 'Площадь 1905г.'), ('ДИН', 'Динамо'), ('УРЛСК', 'Уральская'), ('МАШ', 'Машиностроителей'), ('УРЛМ', 'Уралмаш'), ('ПР', 'Проспект Космонавтов'), ('ДЕПО', 'Депо Калиновское')], default='Склад', max_length=50, verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Склад', editable=False, max_length=6, unique=True, verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер полки')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARM.rack')),
            ],
            options={
                'verbose_name': 'Полка',
                'verbose_name_plural': 'Полки',
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.station', verbose_name='Станция'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер места')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARM.shelf', verbose_name='Полка')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'нужна замена'), ('send', 'отправлен'), ('overdue', 'просрочен'), ('normal', 'сроки в норме'), ('in_progress', 'готовится')], max_length=20, verbose_name='Статус')),
                ('device_type', models.CharField(max_length=20, verbose_name='Тип прибора')),
                ('contact_type', models.CharField(choices=[('contact', 'контактная'), ('contactless', 'бесконтактная')], max_length=20, verbose_name='Наличие контактов')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('inventory_number', models.IntegerField(default=0, verbose_name='Инвентарный номер')),
                ('manufacture_date', models.DateField(verbose_name='дата производства')),
                ('frequency_of_check', models.IntegerField(default=0, null=True, verbose_name='периодичность проверки')),
                ('current_check_date', models.DateField(verbose_name='дата проверки')),
                ('next_check_date', models.DateField(verbose_name='дата следующей проверки')),
                ('avz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.avz', verbose_name='АВЗ')),
                ('mounting_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.place', verbose_name='Монтажный адрес')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.station', verbose_name='Станция')),
                ('who_checked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to=settings.AUTH_USER_MODEL, verbose_name='кто проверил')),
                ('who_prepared', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparer', to=settings.AUTH_USER_MODEL, verbose_name='кто готовил')),
            ],
            options={
                'verbose_name': 'Прибор',
                'verbose_name_plural': 'Приборы',
            },
        ),
        migrations.AddField(
            model_name='avz',
            name='station',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ARM.station'),
        ),
    ]
