# Generated by Django 4.1 on 2023-04-30 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AVZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'АВЗ',
                'verbose_name_plural': 'АВЗ',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ready', 'нужна замена'), ('send', 'отправлен'), ('overdue', 'просрочен'), ('normal', 'сроки в норме'), ('in_progress', 'готовится'), ('decommissioned', 'списан'), ('replaced', 'заменен')], max_length=20, verbose_name='Статус')),
                ('contact_type', models.CharField(choices=[('contact', 'контактная'), ('contactless', 'бесконтактная')], max_length=20, null=True, verbose_name='Наличие контактов')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название')),
                ('inventory_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Инв. номер')),
                ('manufacture_date', models.DateField(null=True, verbose_name='дата производства')),
                ('frequency_of_check', models.IntegerField(default=0, null=True, verbose_name='периодичность проверки')),
                ('current_check_date', models.DateField(verbose_name='дата проверки')),
                ('next_check_date', models.DateField(verbose_name='дата следующей проверки')),
                ('avz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.avz', verbose_name='АВЗ')),
            ],
            options={
                'verbose_name': 'Прибор',
                'verbose_name_plural': 'Приборы',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('БТ', 'Ботаническая'), ('ЧК', 'Чкаловская'), ('ГЕОЛ', 'Геологическая'), ('ПЛ', 'Площадь 1905г.'), ('ДИН', 'Динамо'), ('УРЛСК', 'Уральская'), ('МАШ', 'Машиностроителей'), ('УРЛМ', 'Уралмаш'), ('ПР', 'Проспект Космонавтов'), ('ДЕПО', 'Депо Калиновское'), ('ИНЖ. КОРПУС', 'Инж. Корпус')], default='Склад', max_length=50, verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Склад', editable=False, max_length=6, unique=True, verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Tipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Тип прибора')),
            ],
            options={
                'verbose_name': 'Тип прибора',
                'verbose_name_plural': 'Типы приборов',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, null=True, verbose_name='Статив')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Статив',
                'verbose_name_plural': 'Стативы',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер места')),
                ('rack', models.ForeignKey(help_text='Введите номер статива и выберите значение из списка результатов', on_delete=django.db.models.deletion.CASCADE, to='ARM.rack', verbose_name='Статив')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='MechanicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Краткое пояснение, например 'просрок', 'заменить в этом месяце' и т.д. Не более 30 символов", max_length=30, verbose_name='Заголовок')),
                ('explanation', models.TextField(blank=True, max_length=300, verbose_name='Пояснение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('devices', models.ManyToManyField(help_text='Поиск по названию, но лучше по инвентарному номеру для точности', related_name='marked_devices', to='ARM.device', verbose_name='Помеченные приборы')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARM.station', verbose_name='Станция')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Отчет механика',
                'verbose_name_plural': 'Отчеты механиков',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(help_text='Начните вводить тип прибора и выберите нужное значение из списка', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.tipe', verbose_name='Тип прибора'),
        ),
        migrations.AddField(
            model_name='device',
            name='mounting_address',
            field=models.ForeignKey(blank=True, help_text='Введите статив и выберите нужный адрес из списка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.place', verbose_name='Монтажный адрес'),
        ),
        migrations.AddField(
            model_name='device',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.station', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='device',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.stock', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='device',
            name='who_checked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to=settings.AUTH_USER_MODEL, verbose_name='кто проверил'),
        ),
        migrations.AddField(
            model_name='device',
            name='who_prepared',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparer', to=settings.AUTH_USER_MODEL, verbose_name='кто готовил'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=150, verbose_name='Комментарий')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('mech_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARM.mechanicreport', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='avz',
            name='station',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ARM.station', verbose_name='Станция'),
        ),
    ]
