# Generated by Django 4.1.3 on 2023-04-14 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.stock', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='avz',
            name='station',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ARM.station', verbose_name='Станция'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mounting_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.place', verbose_name='Монтажный адрес'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Название'),
        ),
    ]
