# Generated by Django 4.1 on 2023-04-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='contact_type',
            field=models.CharField(choices=[('contact', 'контактная'), ('contactless', 'бесконтактная')], max_length=20, null=True, verbose_name='Наличие контактов'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(help_text='Начните вводить тип прибора и выберите нужное значение из списка', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARM.tipe', verbose_name='Тип прибора'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Статив'),
        ),
        migrations.AlterField(
            model_name='tipe',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Тип прибора'),
        ),
    ]
