# Generated by Django 4.1 on 2023-05-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='current_check_date',
            field=models.DateField(null=True, verbose_name='дата проверки'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='device',
            name='next_check_date',
            field=models.DateField(null=True, verbose_name='дата следующей проверки'),
        ),
    ]
