# Generated by Django 4.1 on 2023-05-06 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ARM', '0002_alter_device_current_check_date_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, choices=[('нужна замена', 'нужна замена'), ('отправлен', 'отправлен'), ('просрочен', 'просрочен'), ('сроки в норме', 'сроки в норме'), ('готовится', 'готовится'), ('списан', 'списан'), ('заменен', 'заменен')], max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='KipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('explanation', models.TextField(blank=True, max_length=300, verbose_name='Пояснение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='kip_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kip_report', to='ARM.kipreport', verbose_name='Присутствует в отчете КИП'),
        ),
    ]
