# Generated by Django 4.1 on 2023-04-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0002_alter_device_contact_type_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, choices=[('ready', 'нужна замена'), ('send', 'отправлен'), ('overdue', 'просрочен'), ('normal', 'сроки в норме'), ('in_progress', 'готовится'), ('decommissioned', 'списан'), ('replaced', 'заменен')], max_length=20, verbose_name='Статус'),
        ),
    ]
