# Generated by Django 4.1.3 on 2023-04-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0002_device_stock_alter_avz_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventory_number',
            field=models.IntegerField(default=0, verbose_name='Инв. номер'),
        ),
    ]
