# Generated by Django 4.1.3 on 2023-04-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0003_alter_device_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, choices=[('ready', 'нужна замена'), ('send', 'отправлен'), ('overdue', 'просрочен'), ('normal', 'сроки в норме'), ('in_progress', 'готовится')], max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='MechanicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.ManyToManyField(related_name='marked_devices', to='ARM.device')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARM.station', verbose_name='Станция')),
            ],
        ),
    ]
