# Generated by Django 4.1 on 2023-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0003_alter_devicekipreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicekipreport',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата регулировки'),
        ),
        migrations.AlterField(
            model_name='device',
            name='contact_type',
            field=models.CharField(choices=[('контактная', 'контактная'), ('бесконтактная', 'бесконтактная')], max_length=20, null=True, verbose_name='Наличие контактов'),
        ),
        migrations.AlterField(
            model_name='devicekipreport',
            name='mounting_address',
            field=models.CharField(help_text="Если прибор готовится в АВЗ какой-то станции, укажите станцию и впишите в это поле 'авз'.", max_length=10, verbose_name='Монтажный адрес или АВЗ'),
        ),
    ]
