# Generated by Django 4.1 on 2023-04-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0003_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Инв. номер'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='number',
            field=models.CharField(max_length=20, null=True, verbose_name='Статив'),
        ),
    ]
