# Generated by Django 4.1.3 on 2023-04-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0004_alter_device_status_mechanicreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicreport',
            name='explanation',
            field=models.TextField(blank=True, max_length=300, verbose_name='Пояснение'),
        ),
        migrations.AlterField(
            model_name='mechanicreport',
            name='devices',
            field=models.ManyToManyField(related_name='marked_devices', to='ARM.device', verbose_name='Помеченные приборы'),
        ),
    ]
