# Generated by Django 4.1 on 2023-04-28 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ARM', '0004_alter_device_inventory_number_alter_rack_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='manufacture_date',
            field=models.DateField(null=True, verbose_name='дата производства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='who_checked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to=settings.AUTH_USER_MODEL, verbose_name='кто проверил'),
        ),
        migrations.AlterField(
            model_name='device',
            name='who_prepared',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparer', to=settings.AUTH_USER_MODEL, verbose_name='кто готовил'),
        ),
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Номер места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rack',
            field=models.ForeignKey(help_text='Введите номер статива и выберите значение из списка результатов', on_delete=django.db.models.deletion.CASCADE, to='ARM.rack', verbose_name='Статив'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(choices=[('БТ', 'Ботаническая'), ('ЧК', 'Чкаловская'), ('ГЕОЛ', 'Геологическая'), ('ПЛ', 'Площадь 1905г.'), ('ДИН', 'Динамо'), ('УРЛСК', 'Уральская'), ('МАШ', 'Машиностроителей'), ('УРЛМ', 'Уралмаш'), ('ПР', 'Проспект Космонавтов'), ('ДЕПО', 'Депо Калиновское'), ('ИНЖ. КОРПУС', 'Инж. Корпус')], default='Склад', max_length=50, verbose_name='Станция'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=150, verbose_name='Комментарий')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Автор', to=settings.AUTH_USER_MODEL)),
                ('mech_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARM.mechanicreport', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
