# Generated by Django 4.1 on 2023-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0004_devicekipreport_check_date_alter_device_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='old_information',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Старая информация'),
        ),
        migrations.AlterField(
            model_name='devicekipreport',
            name='mounting_address',
            field=models.CharField(help_text="Если прибор готовится в АВЗ какой-то станции, укажите станцию и впишите в это поле 'авз'.Если готовите много бесконтактной аппаратуры, например, предохранителей, укажите количество ввиде 'n шт.'", max_length=10, verbose_name='Монтажный адрес или АВЗ'),
        ),
    ]
