# Generated by Django 4.1 on 2023-08-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARM', '0007_kipreport_editable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicreport',
            name='devices',
            field=models.ManyToManyField(help_text='Поиск по названию, но лучше по инвентарному номеру для точности', related_name='marked_devices', to='ARM.device', verbose_name='Отмеченные приборы'),
        ),
    ]
